### PR TITLE
4.7.5 and mobile 2.0.1 spanish translations

### PR DESCRIPTION
**Pull request by salvadorcunat**
Translated announcements and fixed a typo in about.es

### CODE REVIEW

**Comment by dirkhh** [comment]
Thanks for the translations and thanks for catching the editing error!

**Comment by salvadorcunat** [comment]
BTW @dirkhh , have just noticed that later announcement translations (4.7.2 and 4.7.4) weren't synced and the news page and about page translations (probably, couldn't test as it now points to 4.7.5), still brings the english version.  Checked too with .nl translations by @janmulder, and have the same issue.  This used to worked fine until 4.7.1 (by the end of october).

**Comment by dirkhh** [comment]
Crud. So something broke in the translations.
I'll need to find time to dig into that - messing with PHP isn't something that I enjoy (still, better than Python)

**Comment by dirkhh** [comment]
Oh boy. So much fun. NOT.
So at some point my translation aware version of the sync script got overwritten.
That's why things got out of sync.
I was able to replace that with a copy of my previous version, but now things are so far out of sync, that PHP runs out of memory trying to process things.
And I am struggling to get this to work on a post by post basis. There will be a bunch of thrash in this repo while I try to fix this - and that will take time (which I don't have right now).
So - CRUD.
Hopefully I'll get to the point over the weekend where things on the website are correct and match what's in GitHub. How frustrating.

**Comment by dirkhh** [comment]
Can you check if this is fixed now? I spent several hours on trying to make the script work again. It appears I still get the translations into the wrong categories, so right now I need to manually update this as the attempt of automatically updating things failed. But at least the posts should be there now.

**Pull request merged**
